### ISSUE TITLE
Deploy standalone Eirini

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/cf-crd-explorations#11]
# Background
So far, we've been using a pared down cf-for-k8s to deploy Eirini. This is sub optimal and couples explorations to the cf-for-k8s project, with all the dependencies and configuration specifics for a cf-for-k8s cluster.

## Deliverable
* Instructions to deploy a standalone Eirini Controller (or Eirini if the Controller is not sufficient).
* If deployment configuration is required, that configuration should also be delivered to this repo.

### Dev Notes
* Work should be delivered on a branch, using a PR workflow [referencing this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by angelachin** [comment]
Once [this issue](https://github.com/cloudfoundry-incubator/eirini-ci/issues/21) is completed, we should be able to use a helm chart in the [standalone eirini-controller repo](https://github.com/cloudfoundry-incubator/eirini-controller) to deploy.

**Comment by angelachin** [comment]
Instructions on how to deploy are here: https://github.com/cloudfoundry-incubator/eirini-controller/blob/master/README.md

I think this story just becomes updating our README to reference this.
