### ISSUE TITLE
Explore: Authorization

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-crd-explorations#17]
# Background

Currently, CF on VMs relies on UAA for authentication and looks at specific permissions for roles for authorization. These CF user roles are heavily coupled with the existing CC database. We want to understand what authorization would look like in CF-on-K8s, with CRDs as the source of truth and a shim exposing the CF API.

In particular, we'd like to answer the following questions:
* What's the best [authorization](https://kubernetes.io/docs/reference/access-authn-authz/authorization/) strategy for our use case?
  - we want to be able to express the same [roles and permissions](https://docs.cloudfoundry.org/concepts/roles.html) available on CF
  - we can assume a mapping from *orgs* to *clusters* and from *spaces* to *namespaces* for now, so we could technically map *Org roles* to `ClusterRole`s and *Space roles* to `Role`s
    - this ignores *Admin/Global* roles which work across orgs, but we can assume a single org for now
  - we could go for pure Kubernetes RBAC, if our CRD structure mapped every [operation subject to permission](https://docs.cloudfoundry.org/concepts/roles.html#-roles-and-permissions-for-active-orgs) to a CRUD operation on CRDs: is this the case in the [current proposal](https://github.com/cloudfoundry/cf-crd-explorations#related-docs)?
  - we could use something more sophisticated like the [Open Policy Agent (OPA)](https://www.openpolicyagent.org/)
    -  in this case we wouldn't be storing permissions in `(Cluster)?Role`s and `(Cluster)?RoleBinding`s, so where could we store them?
  - how does this map to [`cf set/unset-org/space-role`](https://docs.cloudfoundry.org/adminguide/cli-user-management.html#org-and-app-space-roles) and `cf org/space-users`?

# Resources

* [CF on K8s Auth N/Z](https://docs.google.com/document/d/1xt9bF7W43X_l_AfYoxoiTmWwIKKgPOz-Wk6FiRx2O24/edit)

# Deliverables

* A document with all our findings
* Can we successfully map the permissions currently available in CF with our chosen authorization solution?

**Comment by angelachin** [comment]
> we could go for pure Kubernetes RBAC, if our CRD structure mapped every operation subject to permission to a CRUD operation on CRDs: is this the case in the current proposal?
Perhaps this is a separate explore to see how the current CRDs map to all the roles we support.

By default, we should see if we can solve authorization just with Kubernetes RBAC and avoid fancier integrations. If not, it'll be helpful to call out what we can't solve with RBAC alone.

A final thing to consider is making sure the authorization experience stays the same for users via the CF cli/api and via kubectl.

**Comment by gcapizzi** [comment]
Closing as this has been split into #35 and #36!
