### ISSUE TITLE
Spike: supporting GKE clusters with Workload Identity Federation

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/cf-crd-explorations#29]
# Background

Some Kubernetes providers don't allow users to configure their clusters to use OIDC for authentication. A notable one is GKE, which [uses OAuth for authentication](https://cloud.google.com/docs/authentication), but not OpenID Connect.

# Questions

Can we use [Workload identity federation](https://cloud.google.com/iam/docs/workload-identity-federation) to authenticate GKE clusters with OIDC?

# Todo: 

- [x]  Delete auth-test cluster
- [x] Remove the Workload Identity Federation config

**Comment by mnitchev** [comment]
We tried to use [workload identity federation](https://cloud.google.com/iam/docs/workload-identity-federation) on GCP together with Dex (as an identity provider), but we realised that in order to get a token from GCP we'd need to use google's client libraries to obt
ain it. The federation gives you a service account config json file that you can use in the GOOGLE_APPLICATION_CREDENTIALS env variable.

Questions:
- If we ever got this to work, would the user appear as the service account, or as the distinct user from the federated IDP?
- This feels like it requires a separate code path in the CLI for both GKE and the particular IDP backend. Is that true? Would that be acceptable?
- If it isn't true that we have to use the client libraires, is there a configuration of the accounts.google.com/o/oauth2/auth url that we can use to get the token?
- Is Pinniped just going to save us all this hassle?

**Comment by kieron-dev** [comment]
- [ ] Foo
- [ ] Bar

**Comment by kieron-dev** [comment]
We reviewed yesterday's investigation into Workload Identity Federation this morning. I wanted to expand the notes slightly so that someone unfamiliar with this can make an informed judgement about it.

We have deployed Dex on a GCP cluster called 'auth-test' with the service exposed on a load-balancer. External address 34.140.130.13 exposed on DNS as dex.34.140.130.13.nip.io, and self-signed certificates used for that domain name. Self-signed certificates seem to prevent the federation working. We see an error when attempting to exchange tokens: 

```
{
  "error": "invalid_grant",
  "error_description": "Error connecting to the given credential's issuer."
}
```

Ideally, we want to see this token exchange process succeed so we can verify the assumption we've made that a user's IDP identity will not be visible to k8s, only the service account associated with the Federation configuration.

## Workload Identity Federation fundamentals

When configuring Workload Identity Federation, the first thing to add is a pool. This is an object for adding a group of backend identity providers (IDPs), users from which will be able to access GCP using a particular service account. You must give a pool an ID, but there is nothing else important configurable on it.

Next, you must add a provider to the pool. There is a choice of 'AWS' or 'OIDC'. For Dex, we chose 'OIDC', and gave it an ID (anything) and specified its issuer URL (defined in Dex).

You can configure some attribute mapping from the backend IDP token into google auth attributes. And finally define some rules to restrict who from the backend IDP can authenticate based on attribute values.

Once a provider as been defined, we can grant access to the pool by associating it with a service account in google. That service account should be given the appropriate permissions to access GCP services as required.

There are instructions on how to use this setup here: https://cloud.google.com/iam/docs/access-resources-oidc.

There is an [automatic flow](https://cloud.google.com/iam/docs/access-resources-oidc#generate-automatic), where gcloud libraries handle getting the gcloud auth token, and a [manual flow](https://cloud.google.com/iam/docs/access-resources-oidc#exchange-token) where the client app must exchange the IDP's token for a gcloud token using a couple of API calls.

In the automatic flow, the client library uses the env var `GOOGLE_APPLICATION_CREDENTIALS` which points to a config file that specifies the path to a file containing the user's active IDP token. The library will make the API calls to convert the token to a gcp token, and then use that in subsequent API requests. It is the responsibility of the client app to ensure the file containing the IDP token always contains an up-to-date token.

## What does this mean for CF CLI and the Shim?

- We would need a CF CLI login plugin specific to GKE that would get an auth token from Dex, and probably manually convert it to a gcloud token, then store that in `~/.cf/config.json`
- That token will be associated with the service account defined in Workload Identity Federation, not the user from the Dex token, although that user can be mapped into another google user attribute
- The Shim would perform user actions on behalf of the service account, rather than the user.

## What does this mean for direct users of the CF cluster?

- We would need to provide a helper program or kubectl plugin to automate logging in with Dex, and converting the id token to a gcloud auth token, and storing it in `~/.kube/config`, similar to the GKE CF CLI login plugin above.
- And again, as above, once inside kubernetes, the current user would be the service account associated with the Workload Identity Federation configuration, not the end user from the IDP.
- RBAC would not be able to distinguish different end users from the IDP, and so could not authorise based on user or group

## Verdict

If the assumption about the service account identity being used in k8s rather than the actual user's ID, then this approach is incompatible with the goal of using out-of-the-box k8s RBAC to perform authorisation. The user's ID can be made available as an additional attribute on the auth object, so custom authorisation would be able to use it - if we need to use that approach.

**Comment by kieron-dev** [comment]
Update on previous comment:

We set up the Workload Identity Federation to also use AWS, which seems to be better integrated with GCP.

After finally running a k8s client command to list pods on an EC2 VM (with an IAM role assigned to it), we got the following error:

```
pods is forbidden: User "wif-dex-test@cff-eirini-peace-pods.iam.gserviceaccount.com" cannot list resource "pods" in API group "" in the namespace "default": requires one of ["container.pods.list"] permission(s).
```

This confirms the suspicion that we don't have the actual user name available in k8s RBAC, just the service account name (wif-dex-test) and that is common to all IdP users.

So Workload Identity Federation is **not** a viable option for us if we want to use native RBAC in k8s.

**Comment by gcapizzi** [comment]
@kieron-dev thanks for the amazing writeup! It looks like federation allows users to abstract OIDC behind Google's OAuth, not the other way around, so it wouldn't differ from just authenticating with Google OAuth. They'd be able to use their users if they have an existing OIDC provider, but the authentication flow and protocol would still be Google's :/

**Comment by kieron-dev** [comment]
> It looks like federation allows users to abstract OIDC behind Google's OAuth, not the other way around, so it wouldn't differ from just authenticating with Google OAuth. They'd be able to use their users if they have an existing OIDC provider, but the authentication flow and protocol would still be Google's ☹️

Yep - you authenticate with your own IdP somehow, then take that id token and exchange it using GCP API endpoints to get a google auth token, and that's what you pass to the k8s API. So you get the inconvenience of 2 auth flows, and you lose your identity in the process, multiple users appearing as a single service account to GCP / GKE.
