### ISSUE TITLE
Explore: unattended login for `cf`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-crd-explorations#42]
# Background

Many users run the `cf` CLI unattended (e.g. in CI). Authentication in these cases is very easy as [`cf login`](https://cli.cloudfoundry.org/en-US/v6/login.html) supports a `-p` argument to provide the password from the command line.

# Questions

Can we achieve something similar when authenticating via `$KUBECONFIG`?

**Comment by kieron-dev** [comment]
I've described a couple of options in passing [here](https://docs.google.com/document/d/1va6sE5uRi_iwGx5nzBcar145_jHq81i9SpwvpUdmsBA/edit#heading=h.jv9ovc7wavfs)

**Comment by kieron-dev** [comment]
Using k8s service account tokens is a great way to authenticate with a single cluster, regardless of the authentication mode set up on the cluster. Service account validation is built into all kubernetes. See example [here](https://github.com/eirini-playground/auth-explore/blob/6e121c3ac10a279dd551b914f7483a7e9218d430/unattended/create-service-account.sh), where we script service account creation, token extraction and use it with a cluster role binding to list pods.

However service accounts are specific to a cluster, so if we need to authenticate across clusters, this method does not work. What would work multi-cluster depends on the authentication mechanism employed there. E.g. 

* GKE using gcloud IAM
    * Log into gcloud using gcloud service account credentials (json file), and generate a kube config
    * kube config will contain a gcp auth-provider section containing a token that is currently valid
    * cf cli will sent that token, and that will be validated by the cluster against gcloud, so will authenticate on any cluster.
* AKS using Azure users or Azure AD
   * Similar to GKE, but using `az` commands
* Any cluster with OIDC configured
   * Get a token from the backend OIDC IDP
   * Include that token in-line in the kube-config
* Any cluster using pinniped
   * Get token from backend IDP (varies by IDP)
   * Alter the exec config of kube-config to include the token using --static-token
* Kind
    * Create a client certificate and private key pair with a long expiry
    * Use these in the kube-config

**Comment by kieron-dev** [comment]
Doc updated.

**Comment by gcapizzi** [comment]
Are there things we could do to make people's life easier in those situations, e.g. adding CLI flags for tokens / certs / CAs?

**Comment by kieron-dev** [comment]
We can always do the equivalent by manipulating the kube.config either directly or with `kubectl config set-credentials`. Whether we need to provide the same directly in the CLI remains to be seen. Maybe we should hold back on adding cf on k8s specific flags to the CLI until we see what the appetite (and tolerance) for them is.
