### ISSUE TITLE
Spike: support `client-go` `auth-provider`s

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-crd-explorations#64]
# Background

We now believe that the best way to support authentication against all different types of Kubernetes clusters is to [use `$KUBECONFIG`](https://github.com/cloudfoundry/cf-crd-explorations/issues/62). The explore describes the different types of authentication `$KUBECONFIG` supports. We believe we can support all of them (except the deprecated ones).

# Questions

Among the different `auth-provider` configs, OIDC is the only one which is not getting deprecated. We believe we can support it, as it stores the ID and refresh tokens we're used to, but we want to make sure we can do this fully. In particular, we want to confirm that we can [refresh the token](https://github.com/cloudfoundry/cf-crd-explorations/issues/37) when necessary. Obtaining the token is out of scope, as it is assumed that the user has already done it at this point.

**Comment by gcapizzi** [comment]
Instead of trying to support the `oidc` `auth-provider` in particular, today we managed to find a way to support all `auth-provider`s generically!

`auth-provider`s implement an [`AuthProvider`](https://pkg.go.dev/k8s.io/client-go@v0.21.3/rest#AuthProvider) interface which has a `WrapTransport` method, taking an [`http.RoundTripper`](https://pkg.go.dev/net/http#RoundTripper) and wrapping it. We found this to be remarkably similar to the [`ConnectionWrapper`](https://github.com/cloudfoundry/cli/blob/c4f9c5b75f03b408c04d58789a1ced1ab9b96f04/api/cloudcontroller/ccv3/connection_wrapper.go#L9-L12) interface in the CF CLI! The `ConnectionWrapper` wraps a [`Connection`](https://github.com/eirini-forks/cli/blob/ebbc342a438438418c97ff9da202a7e8e3d0e4dd/api/cloudcontroller/connection.go#L16-L18), which has a very similar interface to `http.RoundTripper`, so we were able to implement [`ConnectionRoundTripper`](https://github.com/eirini-forks/cli/commit/e08e96bfedffa00869eb79501e8517379f1483ca), an adapter from `Connection` to `RoundTripper`. This could then be wrapped with `AuthProvider.WrapTransport()` and then used!

This proved to work with the `gcp` `auth-provider` and we believe it would work with all of them, including `oidc`. This approach allows to reuse a lot of code, including persisting tokens in `$KUBECONFIG`, which needs to be protected by locks to avoid races.

At the end of the day, we looked at using a similar approach for `exec` plugins, but we had no luck. The `exec` plugins modify the TCP configuration of the HTTP client to be able to inject client certificates, and getting those out seems complicated. We might give this a second shot but our previous approach, invoking the executable directly, looks simpler. On the other hand, the `client-go` implementation comes with a lot of interesting functionality (e.g. caching) that we don't have (yet).

**Comment by kieron-dev** [comment]
### Update on re-using the client-go exec authenticator code

It is possible to use the code from [exec.go](https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/exec/exec.go). The interface is different from the `auth-provider` code we borrowed above. In this case, we must invoke [`UpdateTransportConfig`](https://github.com/kubernetes/client-go/blob/b7569257b24f99ddbb2de05f3d4e43e9f377e62f/plugin/pkg/client/auth/exec/exec.go#L286) passing a `*transport.Config` that we control.

This does two things. First it sets the `TLS.GetCert` property on the transport config to grab the certificate, if any, from the credentials plugin. Secondly it sets up a wrapper function so a `RoundTripper` can be wrapped by one providing the bearer token from the credentials plugin.

Caching and execution of the credentials plugin is taken care of, so we don't have to worry about that. If the user has to login from the `GetCert()` trigger, a second login will not be required when getting the bearer token.

We can use the `*transport.Config` object to retrieve the client certificate, if any, by calling [`GetCert()`](https://github.com/eirini-forks/cli/blob/06e84d8bdb655239b495d9fe2913d4fa6b3dfb9b/api/cloudcontroller/wrapper/k8s_auth.go#L65). Unfortunately, the PEM cert and key have already been parsed and converted into an `x509.Certificate`. We need them back in PEM format to configure the k8s client, so there is the messy process of [reversing that transformation](https://github.com/eirini-forks/cli/blob/06e84d8bdb655239b495d9fe2913d4fa6b3dfb9b/api/cloudcontroller/wrapper/k8s_auth.go#L71-L87).

We can also invoke the `WrapTransport` method on the `*transport.Config` object to use the `ConnectionRoundTripper` built for the `auth-provider` work. This will add the bearer token if the credentials plugin returned one, and if the authorization header is not already set.

So overall, this appears quite reasonable. The code is slightly verbose given the string of potential errors returned, but using `*transport.Config` doesn't feel _that_ hacky!

**Comment by kieron-dev** [comment]
Note that we can test the client cert part of the credentials plugin by using a pinniped configuration. And to test an credentials plugin that produces a bearer token, targeting a GKE cluster and switching the config to use https://github.com/sl1pm4t/gcp-exec-creds works.
