### ISSUE TITLE
Explore: prepare a proposal for our CLI changes

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-crd-explorations#72]
The bulk of our authentication support work will happen in the [`cf` CLI](https://github.com/cloudfoundry/cli). The idea is to change the CLI so that, when pointed at a `cf-k8s` foundation, it leverages the user's `$KUBECONFIG` and possibly code from `client-go` to authenticate exactly in the same way as `kubectl` would.

In #62 we have proved that we can support `$KUBECONFIG` and reuse a lot of `client-go` functionality, while implementing the same [interface](https://github.com/cloudfoundry/cli/blob/master/api/uaa/connection_wrapper.go) the CLI already uses for UAA-based authentication.

Now we need to get a more thorough understanding of all changes needed to implement our strategy. Some questions that come to mind:
* In which part of the codebase are we going to recognise `cf-k8s` and instantiate our `ConnectionWrapper` implementation? Can those two things even happen in the same place with the current architecture?
* Is implementing `ConnectionWrapper` enough to abstract all authentication aspects?
    - We know this is not the case:
        - some packages try to parse the token to get the username out of it;
        - some packages try to refresh the token.
    - Does this mean we need to introduce new abstractions before we can proceed with adding new behaviour?
* How are we going to proceed? Which stories and related PRs do we envision?
    - We already have some [CLI related stories](https://github.com/orgs/cloudfoundry/projects/10?card_filter_query=label%3Aauthn) in the backlog.

The result might look a bit like a [Kubernetes Enhancement Proposal](https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md) although probably not so detailed!

## Deliverable

Let's start this on a Google Doc, and then eventually open a GItHub issue on the CLI repository once we reach agreement in the team.

**Comment by gcapizzi** [comment]
I have taken a quick look at the CLI codebase, and in particular at the [`cf api` command](https://github.com/cloudfoundry/cli/blob/master/command/v7/api_command.go).

The command [delegates](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/command/v7/api_command.go#L60-L64) to [`Actor.SetTarget`](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/actor/v7action/target.go), which, in order:
1. [initialises](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/actor/v7action/target.go#L15) the Cloud Controller client;
1. [calls](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/actor/v7action/target.go#L17) the CF root endpoint;
1. [stores](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/actor/v7action/target.go#L23-L34) the results in the configuration.

`Config` gets [loaded](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/util/command_parser/command_parser.go#L47) in the `CommanParser` and then [passed](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/util/command_parser/command_parser.go#L88) to each command via the `Setup` method. It gets then used to [instantiate the wrapped clients](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/command/v7/api_command.go#L29), so it is [available when the wrappers are wired in](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/command/v7/shared/new_clients.go#L34). This means that we could have a `ConnectionWrapper` which dynamically decides which strategy to use based on the `Config`:
* `ApiCommand` [tells](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/command/v7/api_command.go#L60-L64) the `Actor` to [fetch information about the API](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/actor/v7action/target.go#L17) and to [store them](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/actor/v7action/target.go#L23-L34) into the `Config`;
* Any subsequent command (they all embed [`BaseCommand`](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/command/v7/base_command.go)) receives the `Config` and [injects it](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/command/v7/base_command.go#L29) into its clients, which in turn get [injected](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/command/v7/base_command.go#L36) into the `Actor`;
* [`GetNewClientsAndConnectToCF`](https://github.com/cloudfoundry/cli/blob/d01e54921398cadd1b2b69198ea0a51b0d121762/command/v7/shared/new_clients.go#L34) can then use the `Config` to decide which `ConnectionWrappers` to apply!

**Comment by gcapizzi** [comment]
Today I systematically searched for all the code paths that used a [`UAAClient`](https://github.com/cloudfoundry/cli/blob/master/actor/v7action/uaa_client.go). Here is the list of [`Actor`](https://github.com/cloudfoundry/cli/blob/master/command/v7/actor.go) methods  that do, alongside the commands they get invoked from:

* `Authenticate(credentials map[string]string, origin string, grantType uaa.GrantType) error`
    - `auth`
    - `login`
* `CreateOrgRole(roleType constant.RoleType, orgGUID string, userNameOrGUID string, userOrigin string, isClient bool (v7action.Warnings, error)`
    - `set-org-role`
    - `create-space`
    - `set-space-role`
* `CreateSpaceRole(roleType constant.RoleType, orgGUID string, spaceGUID string, userNameOrGUID string, userOrigin string, isClient bool) (v7action.Warnings, error)`
    - `create-space`
    - `set-space-role`
* `CreateUser(username string, password string, origin string) (resources.User, v7action.Warnings, error)`
    - `create-user`
* `DeleteUser(userGuid string) (v7action.Warnings, error)`
    - `delete-user`
* `GetLoginPrompts() (map[string]coreconfig.AuthPrompt, error)`
    - `login`
* `GetSSHPasscode() (string, error)`
    - `ssh-code`
* `GetSecureShellConfigurationByApplicationNameSpaceProcessTypeAndIndex(appName string, spaceGUID string, processType string, processIndex uint) (v7action.SSHAuthentication, v7action.Warn  ings, error)`
    - `ssh`
* `GetUAAAPIVersion() (string, error)`
    - `auth`
* `GetUser(username, origin string) (resources.User, error)`
    - `create-user`
    - `delete-user`
* `RefreshAccessToken() (string, error)`
    - `logs`
    - `oauth-token`
* `RevokeAccessAndRefreshTokens() error`
    - `logout`
* `ScheduleTokenRefresh(func(time.Duration) <-chan time.Time, chan struct{}, chan struct{}) (<-chan error, error)`
    - `logs`
* `UpdateUserPassword(userGUID string, oldPassword string, newPassword string) error`
    - `passwd`

Some observations:
* We probably want these methods to belong to a separate `interface` that we can implement differently for `cf-k8s`. 
* Some of these methods can be left empty in our implementation, as we don't plan to support the corresponding commands:
    - `Authenticate`, `GetLoginPrompts`, `GetUAAAPIVersion`, `RevokeAccessAndRefreshTokens`, `UpdateUserPassword` are all used by the auth flow commands (`login`, `auth`, `logout`, `passwd`).
    - `CreateUser`, `DeleteUser` and `GetUser` are used in the user management commands (`create-user`, delete-user`).
    - `GetSSHPasscode` and `GetSecureShellConfigurationByApplicationNameSpaceProcessTypeAndIndex` are used in the `ssh*` commands.
* The token refreshing methods (`RefreshAccessToken` and `ScheduleTokenRefresh`) are needed by `log` to keep the access token fresh while streaming logs.
    - Note that this has nothing to do with the CC client and the `ConnectionWrapper`, as the logs are streamed from Log Cache via a [`LogCacheClient`](https://github.com/cloudfoundry/cli/blob/master/command/log_cache_client.go), which is [wired](https://github.com/cloudfoundry/cli/blob/ef091af950f3f184b9051f85185f212836a5a38a/command/log_cache_client.go#L126) to use the `Config.AccessToken` method as its token-generating function.
    - `RefreshAccessToken` mutates the `Config` which then returns the new token to `LogCacheClient`: `Config` is effectively used as shared mutable state.
    - One way to solve this is to keep these methods empty and instead find a way to provide `LogCacheClient` with a different token-generating function, or just replace the `http.Client` getting injected altogether. Can we implement a wrapper to `http.Client`? `client-go` abstractions are built upon `http.RoundTripper` but maybe we can make it work?
* `CreateOrgRole` and `CreateSpaceRole` are interesting: we definitely want to implement these, but I'm still not sure how.

**Comment by gcapizzi** [comment]
@emalm had an interesting question on our [authentication doc](https://docs.google.com/document/d/1va6sE5uRi_iwGx5nzBcar145_jHq81i9SpwvpUdmsBA/edit#): can we leverage `cf login` to allow users to choose their `context` vs trying to detect it automatically? The answer is yes!

Here is how we could do this:
* [`LoginCommand`](https://github.com/cloudfoundry/cli/blob/5ffa262bb2e51ba770d456fd169da89ca0b9801f/command/v7/login_command.go) calls `Actor.GetLoginPrompts` to get a list of prompts to submit to the user via the [`UI`](https://github.com/cloudfoundry/cli/blob/5ffa262bb2e51ba770d456fd169da89ca0b9801f/command/ui.go).
* Each [`AuthPrompt`]() has a `Type`, currently either `TEXT` or `PASSWORD`. Different `UI` methods are called based on this.
* The resulting credentials are then [passed](https://github.com/cloudfoundry/cli/blob/5ffa262bb2e51ba770d456fd169da89ca0b9801f/command/v7/login_command.go#L300) to `Actor.Authenticate`.
* By providing different implementations of both `GetLoginPrompts` and `Authenticate`, we could prompt the user for the `context` they want to use, and store it in the `Config`.
* Given `context`s tend to have long and hard-to-type names, we could introduce a new `AuthPrompt.Type` called `MENU` and use [`UI.DisplayTextMenu`](https://github.com/cloudfoundry/cli/blob/5ffa262bb2e51ba770d456fd169da89ca0b9801f/command/ui.go#L35) for it.
* The list of menu entries could be stored in `AuthPrompt.DisplayName` (e.g. separated by commas) or in a new `Entries` field.

**Comment by gcapizzi** [comment]
Methods trying to parse the JWT token:
* `Actor`
    - `RefreshAccessToken() (string, error)`
    - `ScheduleTokenRefresh(func(time.Duration) <-chan time.Time, chan struct{}, chan struct{}) (<-chan error, error)`
    - `ParseAccessToken(string) (jwt.JWT, error)`
* `UAAAuthentication.Make(*cloudcontroller.Request, *cloudcontroller.Response) error`
* `Config`
    - `CurrentUser() (User, error)`
    - `CurrentUserName() (string, error)`

The `Actor` methods are only invoked in `cf logs` and `cf oauth-token`, which we can ignore for now. We're going to provide an alternative `ConnectionWrapper` implementation to `UAAAuthentication`, so we don't care about that either. 

Unfortunately the `Config` methods are called literally *everywhere* 😞  and while the vast majority of commands only use it to print user info on screen, some don't. For example the `CreateSpaceCommand` actually [sends the username](https://github.com/cloudfoundry/cli/blob/5ffa262bb2e51ba770d456fd169da89ca0b9801f/command/v7/create_space_command.go#L104) to the Cloud Controller in the creation request.

In these cases, even if we stored the username from `$KUBECONFIG` (see my [previous comment](https://github.com/cloudfoundry/cf-crd-explorations/issues/72#issuecomment-905494682)), it would be insecure to use it as anyone could impersonate anyone else just by changing their config.

**Comment by danail-branekov** [comment]
We started hacking the cli and try to integrate it with cfshim and we scoredcertain progress.

Setting up the dev environment:
* Checkout the [auth-explore](https://github.com/eirini-playground/auth-explore)
* Checkout the `wip-auth` brach of [cf-crd-explorations](https://github.com/cloudfoundry/cf-crd-explorations/tree/wip-auth)
* Checkout the `wip-k8s` branch of our [cli fork](https://github.com/eirini-forks/cli/tree/wip-k8s)
* Create a kind cluster with dex and cfshim CRs via running the [deploy.sh script](https://github.com/eirini-playground/auth-explore/blob/master/run-cfshim/deploy.sh)
* Run the cfshim with [run.sh](https://github.com/eirini-playground/auth-explore/blob/master/run-cfshim/run.sh) (I got bored and frustrated trying to make it run on the kind cluster)
* Get yourself a token for `alice@vcap.me` and put it in the kubeconfig, see this [README](https://github.com/eirini-playground/auth-explore/blob/master/dex-auth/README.md) for details. No need to login with github, just use the email login on the dex page
* Build the `cli` fork

Behold!

* **target**

```
❯ ./cli api http://localhost:9000
Setting API endpoint to http://localhost:9000...
Warning: Insecure http API endpoint detected: secure https API endpoints are recommended
OK

API endpoint:   http://localhost:9000
API version:

Not logged in. Use 'cli login' or 'cli login --sso' to log in.

```

* **login**

```
❯ ./cli login
API endpoint: http://localhost:9000
Warning: Insecure http API endpoint detected: secure https API endpoints are recommended
Warning: unable to determine whether targeted API's version meets minimum supported.

1. alice
2. gke_cff-eirini-peace-pods_europe-west1-b_cf4k8s4a8e
3. gke_cff-eirini-peace-pods_europe-west1-b_dex-pinniped
4. gke_cff-eirini-peace-pods_europe-west1-b_pinniped
5. kind-cross-org-1
6. kind-cross-org-2
7. kind-dex-play

Choose your Kubernetes user (enter to skip): 1

Authenticating...
OK

Targeted org foo.

Targeted space bar.

API endpoint:   http://localhost:9000
API version:
user:           alice
org:            foo
space:          bar
```

The cli would show a menu with the entries from kubeconfig, note that `alice` is there! After being chosen, the UI reports that you are logged in as `alice`

* **apps**

```
❯ ./cli apps
Getting apps in org foo / space bar as alice...

Unexpected Response
Response Code: 500
Code: 0, Title: , Detail: {"errors":[{"detail":"error fetching app: apps.apps.cloudfoundry.org is forbidden: User \"oidc:alice@vcap.me\" cannot list resource \"apps\" in API group \"apps.cloudfoundry.org\" at the cluster scope","title":"ServerError","code":10001}]}

FAILED
```

Good, we are hitting the shim with alice's JWT token so K8S knows who we are. `alice` is not allowed to do that though... yet

```
❯ k apply -f ~/workspace/auth-explore/run-cfshim/alice-viewer-rolebinding.yml
clusterrolebinding.rbac.authorization.k8s.io/alice-viewer created
clusterrole.rbac.authorization.k8s.io/app-viewer created
clusterrolebinding.rbac.authorization.k8s.io/alice-apps-viewer created

❯ ./cli apps
Getting apps in org foo / space bar as alice...

No apps found
```

Let's create an app and try to list it:

```
❯ k apply -f ~/workspace/cf-crd-explorations/config/samples/cf-crds/app.yaml
app.apps.cloudfoundry.org/my-app-guid created

~/workspace/cli wip-k8s
❯ ./cli apps
Getting apps in org foo / space bar as alice...

Error unmarshalling the following into a cloud controller error: 404 page not found

FAILED

```

Well, we will figure that out next.

**Comment by mnitchev** [comment]
Blocking until the rest of the team can take a look at the draft proposal [here](https://docs.google.com/document/d/1SM0AH0E9Oy0ej9EvJf0OrXZbxixEr2Imu59C3xgwnOw/edit?usp=sharing)

**Comment by emalm** [comment]
@mnitchev, could you please grant global comment-level access to that proposal doc? Thanks!

**Comment by kieron-dev** [comment]
@emalm - global comment-level enabled.
