### ISSUE TITLE
Explore virtual clusters

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/cf-crd-explorations#79]
https://github.com/kubernetes-sigs/cluster-api-provider-nested/tree/main/virtualcluster

Could be useful for orgs/spaces separation.

**Comment by danail-branekov** [comment]
1. The concept of virtual clusters could be useful to implement isolation segments.
1. The project is not mature, its latest release is 0.1.0 but it does not work out of the box.
1. While following the demo script we noticed that deployments are visible within the virtual cluster only, but their pods are actually running on the host cluster. This defeats the usage or virtual clusters for isolation segments as an erroneous network configuration could cause pods of different tenants to be able to talk to each other)

The points above made us think that for the time being it is not worth investing efforts into exploring virtual clusters.
